name: C/C++ CI

on:
  push:
    branches:
      - Development
  pull_request:
    branches:
      - Development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup GRPC
      run: |
        if [ ! -d "$HOME/.local/include/grpc" ]; then
          sudo apt-get update
          export MY_INSTALL_DIR=$HOME/.local
          mkdir -p $MY_INSTALL_DIR
          export PATH="$MY_INSTALL_DIR/bin:$PATH"
          sudo apt install -y cmake
          sudo apt install -y build-essential autoconf libtool pkg-config
          git clone --recurse-submodules -b v1.60.0 --depth 1 --shallow-submodules https://github.com/grpc/grpc
          cd grpc
          mkdir -p cmake/build
          pushd cmake/build
          cmake -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=$MY_INSTALL_DIR ../..
          make
          make install
          popd
        else
          echo "gRPC already installed, skipping setup."
        fi

    - name: Build and test Asynchronous GRPC Unary
      run: |
        cd "grpc asynchronous/grpc_unary"
        mkdir build
        cd build
        cmake ..
        make

    - name: Build and test Asynchronous GRPC Generalized
      run: |
        cd ".."
        cd "grpc_unary_generalized"
        mkdir build
        cd build
        cmake ..
        make

    - name: Build and test Synchronous GRPC Basic
      run: |
        cd ".."
        cd ".."
        cd "grpc synchronous/grpc_basic/"
        mkdir build
        cd build
        cmake ..
        make

    - name: Build and test Synchronous GRPC Bidirectional Stream
      run: |
        cd ".."
        cd "grpc_bidirectional_stream"
        mkdir build
        cd build
        cmake ..
        make

    - name: Build and test Synchronous GRPC Server Stream
      run: |
        cd ".."
        cd "grpc_server_stream"
        mkdir build
        cd build
        cmake ..
        make

    - name: Build and test Synchronous GRPC Unary
      run: |
        cd ".."
        cd "grpc_unary"
        mkdir build
        cd build
        cmake ..
        make
