name: C/C++ CI

on:
  push:
    branches:
      - Development
  pull_request:
    branches:
      - Development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and test A folder
      run: |
        cd "grpc asynchronous"
        mkdir build
        cd build
        cmake ..
        make
        make test

    - name: Build and test B folder
      run: |
        cd "../grpc synchronous"
        mkdir build
        cd build
        cmake ..
        make
        make test
