name: C/C++ CI

on:
  push:
    branches:
      - Development
  pull_request:
    branches:
      - Development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and test Asynchrounous GRPC Unary
      run: |
        cd "grpc asynchronous/grpc_unary"
        mkdir build
        cd build
        cmake ..
        make
        make test
    
    - name: Build and test Asynchrounous GRPC Generalized
      run: |
        cd "../grpc_unary_generalized"
        mkdir build
        cd build
        cmake ..
        make
        make test

    - name: Build and test synchrounous GRPC Basic
      run: |
        cd "../../grpc synchronous/grpc_basic/"
        mkdir build
        cd build
        cmake ..
        make
        make test
    
    - name: Build and test synchrounous GRPC Bidirectional Stream
      run: |
        cd "../grpc_bidirectional_stream"
        mkdir build
        cd build
        cmake ..
        make
        make test
    - name: Build and test synchrounous GRPC Server Stream
      run: |
        cd "../grpc_server_stream"
        mkdir build
        cd build
        cmake ..
        make
        make test
    - name: Build and test synchrounous GRPC Unary
      run: |
        cd "../grpc_unary"
        mkdir build
        cd build
        cmake ..
        make
        make test
