name: C/C++ CI

on:
  push:
    branches:
      - Development
  pull_request:
    branches:
      - Development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Protobuf
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler libprotobuf-dev

    - name: Set CMAKE_PREFIX_PATH for Protobuf
      run: |
        echo "::set-env name=CMAKE_PREFIX_PATH::/usr/lib/x86_64-linux-gnu/cmake/protobuf"

    - name: Build and test Asynchronous GRPC Unary
      run: |
        cd "grpc asynchronous/grpc_unary"
        mkdir build
        cd build
        cmake ..
        make
        make test
    
    - name: Build and test Asynchronous GRPC Generalized
      run: |
        cd "../grpc_unary_generalized"
        mkdir build
        cd build
        cmake ..
        make
        make test

    - name: Build and test Synchronous GRPC Basic
      run: |
        cd "../../grpc synchronous/grpc_basic/"
        mkdir build
        cd build
        cmake ..
        make
        make test
    
    - name: Build and test Synchronous GRPC Bidirectional Stream
      run: |
        cd "../grpc_bidirectional_stream"
        mkdir build
        cd build
        cmake ..
        make
        make test
    
    - name: Build and test Synchronous GRPC Server Stream
      run: |
        cd "../grpc_server_stream"
        mkdir build
        cd build
        cmake ..
        make
        make test
    
    - name: Build and test Synchronous GRPC Unary
      run: |
        cd "../grpc_unary"
        mkdir build
        cd build
        cmake ..
        make
        make test
